// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACOcsy97MW1N4PLXMY0agFEVDBcuXx-Bk',
    appId: '1:52914604882:web:3e90309a07bbe3750f488b',
    messagingSenderId: '52914604882',
    projectId: 'evently-1c303',
    authDomain: 'evently-1c303.firebaseapp.com',
    storageBucket: 'evently-1c303.firebasestorage.app',
    measurementId: 'G-X1PXZH3Y1D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_g8Vi7qJsdNkcpXCBrVcSg0UiqaBzAao',
    appId: '1:52914604882:android:bb69eb71f01c97050f488b',
    messagingSenderId: '52914604882',
    projectId: 'evently-1c303',
    storageBucket: 'evently-1c303.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApHxtORRWgvK7gThH1AHvtZrLHXtt6ifA',
    appId: '1:52914604882:ios:8aad48aca985f8c90f488b',
    messagingSenderId: '52914604882',
    projectId: 'evently-1c303',
    storageBucket: 'evently-1c303.firebasestorage.app',
    iosBundleId: 'com.example.evently',
  );
}
